version: '3.3'

services:
  db:
    image: mariadb:10
    volumes:
      - db_data:/var/lib/mysql
    restart: on-failure
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress

  wordpress:
    build:
      context: .
      dockerfile: ./docker/wordpress/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    image: carlknappdev/wordpress
    user: '${UID}:${GID}'
    ports:
      - '80:80'
      - '443:443'
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 'true'
    volumes:
      - ./public:/var/www/html

  composer:
    profiles:
      - dev
    build:
      context: .
      dockerfile: ./docker/composer/Dockerfile
      args:
        - UID=${UID}
        - GID=${GID}
    image: wordpress/composer
    container_name: composer

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: on-failure
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      PMA_USER: wordpress
      PMA_PASSWORD: wordpress
      UPLOAD_LIMIT: 50M

volumes:
  db_data: {}
